kind: Service
apiVersion: v1
metadata:
  name: rothstocks-service
  labels:
    app: rothstocks
spec:
  selector:
    app: rothstocks
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
